version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/
    overwrite: yes
    exclude:
      - appspec.yml
hooks:
  AfterInstall:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root
