version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies (if needed)
      # Optionally build/minify files here

  build:
    commands:
      - echo Build phase - nothing to compile

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
